/**
 * Page-level copy for route components under app/.
 * Keep route titles, CTA labels, empty states, and demo hints centralized here.
 */
export const appMetadataCopy = {
  title: "话到嘴边",
  description: "年轻人的场景表达转换器",
} as const;

export const homePageCopy = {
  topLabel: "年轻人的场景表达转换器",
  profileAriaLabel: "我的收藏",
  heroTitle: "话到嘴边",
  heroSubtitleLines: ["把不好开口的话，", "换一种更合适的表达"] as const,
  heroDescription: "帮你把真实想法，转成适合不同对象、不同场景的表达版本",
  recentSectionTitle: "最近使用",
  recentSectionAction: "查看全部",
  recentCardTitle: "关于周末活动分工的沟通",
  recentCardSubtitle: "职场沟通 · 别甩给我",
  recentCardMeta: "刚刚",
  recentEmptyTitle: "还没有最近使用",
  recentEmptySubtitle: "完成一次转换后，这里会显示最近的表达记录",
  recentEmptyAction: "先开始一次",
  hotSectionTitle: "热门风格",
  primaryAction: "开始转换",
} as const;

export const inputPageCopy = {
  title: "你想说的话",
  exampleAction: "示例",
  clearAction: "清空",
  exampleRawText: "这个活不是我负责的，别老找我。",
  sceneSectionTitle: "选择场景",
  sceneSectionHint: "先定沟通语境",
  targetSectionTitle: "选择对象",
  targetSectionHint: "对象会影响语气默认值",
  targetEmptyHint: "请先选择一个场景",
  fieldLabel: "对什么人，说什么话",
  emptySceneHint: "一句原话，也可以有更好的说法",
  textAreaPlaceholder: "在这里输入你想说的话...\n\n例如：这个活不是我负责的，别老找我。",
  overSoftLimitHint: "超过 300 字后可能影响转换聚焦，建议删到最关键的事实和诉求。",
  styleSectionTitle: "选择风格",
  styleSectionHint: "左右滑动选择",
  styleDescriptionTitle: "当前风格",
  readyHint: "左右滑动，选择你喜欢的风格",
  blockedHint: "先选场景、对象和风格，再输入至少 2 个字",
  missingSceneToast: "请先选择沟通场景",
  missingTargetToast: "请先选择沟通对象",
  missingStyleToast: "请先选择表达风格",
  missingTextToast: "请至少输入 2 个字",
  exampleNeedsContextToast: "请先选择场景和对象",
  primaryAction: "开始转换",
} as const;

export const tonePageCopy = {
  title: "语气仪表盘",
  subtitle: "微调语气，让表达更贴近你的意图",
  resetAction: "重置",
  missingDraftTitle: "还差一句原话",
  missingDraftBadge: "待补充",
  missingDraftDescription: "先回到输入页，选择场景并写下你想表达的真实想法。",
  previewTitle: "表达预览",
  previewBadge: "实时预览",
  previewPending: "正在准备当前语气的表达预览...",
  previewLoading: "正在根据当前语气生成预览...",
  previewFailed: "预览生成失败，请稍后重试或直接生成结果。",
  previewRefused: "这句话暂时无法生成，请回到输入页调整原话。",
  contextLabel: "当前上下文",
  quickToneTitle: "快捷调整",
  quickTones: [
    { key: "softer", label: "再软一点" },
    { key: "formal", label: "更正式" },
    { key: "boundary", label: "更有边界感" },
  ] as const,
  previewSamples: {
    formalHigh: "您好，关于您提到的事项目前不在我的负责范围内，建议联系对应负责人确认，我会尽力配合需要的信息。",
    distanceLow: "这个我不太负责诶，可能找对应同事更合适，我可以帮你问问该找谁～",
    politenessHigh: "这件事我这边可能不太负责，建议你联系对应同事确认一下，会更准确一些。",
    default: "我理解你的需求，这个部分目前不在我的负责范围内，我可以帮你确认负责的同事是谁～",
  },
  sliders: {
    politeness: {
      title: "礼貌程度",
      left: "直接",
      right: "礼貌",
      hint: "语气更礼貌，表达更照顾对方感受",
    },
    formality: {
      title: "正式程度",
      left: "日常",
      right: "正式",
      hint: "表达更正式，适合书面或职场场景",
    },
    distance: {
      title: "关系距离",
      left: "熟人",
      right: "陌生/上级",
      hint: "保持适当距离，表达更得体",
    },
  },
  generateAction: "生成结果",
  backToInputAction: "返回输入",
} as const;

export const resultsPageCopy = {
  title: "转换结果",
  subtitle: "根据你的当前草稿实时生成结果",
  saveAction: "收藏",
  saveActiveAction: "已收藏",
  shareAction: "分享",
  originalLabel: "原话",
  editOriginalAction: "重新生成",
  emptyOriginal: "还没有输入原话，请先回到输入页补充。",
  successTitle: "表达版本已生成",
  successDescription: "可以直接复制使用，也可以继续调整语气或换一种风格。",
  metaLanguageLabel: "输出语言",
  languageLabels: {
    "zh-CN": "中文",
    en: "English",
    ja: "日本語",
    ko: "한국어",
  },
  missingDraftTitle: "还不能生成结果",
  missingDraftDescription: "请先选择沟通场景，并输入至少 2 个字的真实想法。",
  missingDraftAction: "返回输入",
  loadingTitle: "正在生成",
  loadingDescription: "正在把你的真实想法转换成更适合发送、书写和当面表达的版本。",
  refusedTitle: "这句话需要换个目标",
  refusedDefaultMessage: "当前表达风险较高，请改为描述事实、影响和诉求。",
  refusedAction: "修改原话",
  failTitle: "生成暂时失败",
  failDefaultMessage: "服务暂时不可用，请稍后再试。",
  retryAction: "重试一次",
  copySuccess: "已复制",
  copyFailed: "复制失败，请手动长按复制",
  favoriteSaved: "已收藏到本机",
  favoriteRemoved: "已取消收藏",
  favoriteUnavailable: "生成结果后才能收藏",
  shareCopied: "已复制分享文本",
  shareFailed: "分享失败，请稍后再试",
  compareAction: "查看“原话 → 优化版”的变化点",
  adjustToneAction: "再调整语气",
  switchStyleAction: "换一种风格",
  styleSheetTitle: "换一种表达风格",
  usefulSaved: "已记录反馈",
} as const;

export const historyPageCopy = {
  title: "历史记录",
  subtitle: "保存在本机的最近 50 次转换",
  clearAction: "清空",
  emptyTitle: "还没有历史记录",
  emptyDescription: "完成一次转换后，这里会显示原话、场景和推荐表达。",
  startAction: "开始转换",
  favoriteLabel: "已收藏",
  openAction: "查看",
} as const;

export const profilePageCopy = {
  title: "我的",
  subtitle: "本机偏好与使用统计",
  statsTitle: "使用统计",
  totalGenerations: "转换次数",
  favoriteCount: "收藏数",
  lastUsedAt: "最近使用",
  emptyDate: "暂无",
  favoritesTitle: "收藏",
  prefsTitle: "偏好",
  prefsDescription: "当前 MVP 使用本机存储，不需要登录。",
  startAction: "开始一次新的转换",
} as const;
